= Ingénierie des systèmes d'information 2

Licence L3 classique, MIAGE, Paris-Dauphine, TD n° 2

L’link:https://www.ent.dauphine.fr/annuaire/index.php?param0=fiche&param1=ocailloux[enseignant].

== Remise
Ces instructions de remise remplacent celles contenues dans l’énoncé. Il ne faut donc pas m’envoyer vos dossiers par e-mail ni m’en remettre des copies papier.

Les séances auxquelles les dossiers doivent avoir été rendus sont indiquées dans le planning. Le dossier doit avoir été rendu avant la fin de la veille de la séance en question. Par exemple, si la séance où le dossier doit être terminé a lieu le lundi 21 janvier, il faut avoir rendu le dossier avant dimanche 20 janvier, 23h59 + 1 min. La pénalité est de 0,5 points / 40 par heure de retard (toute heure entamée est comptée).

Un dossier doit être rendu sous la forme d’un seul document PDF dont le nom doit commencer par un chiffre, correspondant au numéro du dossier (1 pour le dossier de cadrage, et ainsi de suite), suivi d’link:https://fr.wikipedia.org/wiki/Espace_(typographie)[une] espace, d’un trait-d’union, d’une espace, et du nom de votre équipe. Par exemple : `1 - Super Toto.pdf`. La présentation finale compte comme un dossier. Elle donc doit aussi être au format PDF, sauf raison valable approuvée par l’enseignant au préalable, et être rendue à temps.

Chaque groupe doit se créer un dépôt GitHub Classroom en cliquant https://classroom.github.com/g/A0Q2ZHc0[ici]. Vous y déposerez vos dossiers au fur et à mesure de l’année (et rien d’autre). Pour envoyer le fichier, initialement, cliquez sur `uploading an existing file` dans votre dépôt ; après, voir https://help.github.com/articles/adding-a-file-to-a-repository/[ici]. Vous déposez sur la branche `master`. En fin d’année, votre dépôt devra donc contenir exactement cinq fichiers. Vous pouvez écraser un fichier si vous voulez déposer une nouvelle version avant la date limite, il suffit de déposer un fichier de même nom.

== Format
Les exigences ci-dessous ne remplacent pas, mais complémentent, les instructions dans l’énoncé.

Les dossiers PDF (sauf la présentation) doivent contenir des signets PDF référençant les numéros de page corrects (https://screenshots.debian.net/screenshots/000/015/840/large.png[exemple]), reflétant la table des matières qui doit par ailleurs être également incluse dans le document comme demandé dans le document d’énoncé.

Une des vertus attendues de bons analystes est la précision. Tout manquement aux exigences, même sur la forme et même si elles vous semblent triviales, sera sanctionné.

== Contenu
Vous êtes priés d’utiliser des diagrammes UML partout où il est possible de remplacer ou complémenter du texte par des diagrammes appropriés, même lorsque ce n’est pas expressément demandé dans l’énoncé. Un diagramme omis vous coutera la moitié des points, à contenu informatif égal.

Attention à ne pas confondre des notations UML (par exemple, une ligne discontinue n’a pas la même signification qu’une ligne continue). Vos diagrammes doivent de plus être cohérents et non ambigus.

== Cours
Pour le bon fonctionnement du travail en équipe, votre présence à ce cours est obligatoire. Les absences seront sanctionnées.

Vous êtes censés consulter vos e-mails Dauphine fréquemment (pour annonces via MyCourse).

S1 

* Gestion de projet : https://github.com/oliviercailloux/SI2/raw/master/Cours_ISI2_1819.pdf[diapos]
* Présentation du https://github.com/oliviercailloux/SI2/tree/master/Énoncé[projet]
* Répartition des 26 étudiants en groupes de 4 (max 2 groupes de 5) et choix des noms des équipes
* Travail sur Dossier de Cadrage

S2

* Travail sur Dossier de Cadrage 
* Travail sur Dossier de Spécifications Générale [SG]

S3

* *Dossier de Cadrage* terminé
* Travail sur SG

S4

* Travail sur SG

S5

* *SG* terminé
* Remise Orientations Spécifications Fonctionnelles Détaillées
* Travail sur Dossier de Spécification Détaillée [SD]

S6

* Travail sur SD

S7

* Travail sur SD

S8

* Travail sur SD

S9

* *SD* terminé
* Travail sur Dossier Entrepôt [DWH]

S10

* *DWH* terminé
* *Présentation* terminée
* Soutenances
** 19 minutes par groupe + 5 minutes de questions + 2 minutes de transition
** Bonus pour questions pertinentes et non dérangeantes

